services:
  - type: web
    name: 𝐇𝐈𝐒 𝐄𝐗𝐂𝐄𝐋𝐋𝐄𝐍𝐂𝐘~𝐌𝐃
    runtime: node
    plan: free
    buildCommand: npm install 
    startCommand: npm start   
    envVars:
      - key: SESSION-ID
        sync: false
      - key: OWNER
        sync: false
      - key: OWNER-NUMBER
        sync: false
      - key: PREFIX
        sync: false
